# Bài tập về nhà: Singular Value Decomposition (SVD)

Bài làm gồm 2 câu:

1. Phân rã một ma trận rank thấp bằng SVD.
2. Chọn số thành phần $k$ cho Truncated SVD dựa trên tỷ lệ năng lượng.

# Câu 1. Phân rã ma trận

Cho

$$
A=
\begin{bmatrix}
1 & 0 & 1\\
0 & 1 & 1\\
1 & 0 & 1\\
0 & 1 & 1
\end{bmatrix}
\in \mathbb{R}^{4 \times 3}.
$$

Gọi ba cột của $A$ là $a_1, a_2, a_3$:

$$
a_1=
\begin{bmatrix}
1\\
0\\
1\\
0
\end{bmatrix},
\qquad
a_2=
\begin{bmatrix}
0\\
1\\
0\\
1
\end{bmatrix},
\qquad
a_3=
\begin{bmatrix}
1\\
1\\
1\\
1
\end{bmatrix}.
$$

Ta thấy

$$
a_3 = a_1 + a_2.
$$

Vì vậy, các cột của $A$ phụ thuộc tuyến tính. Hai cột $a_1$ và $a_2$ độc lập tuyến tính nên

$$
\mathrm{rank}(A) = 2.
$$

## 1. Tính $A^\top A$

Các tích vô hướng giữa các cột là:

$$
a_1^\top a_1 = 2,\quad
a_2^\top a_2 = 2,\quad
a_3^\top a_3 = 4,
$$

$$
a_1^\top a_2 = 0,\quad
a_1^\top a_3 = 2,\quad
a_2^\top a_3 = 2.
$$

Do đó,

$$
A^\top A =
\begin{bmatrix}
2 & 0 & 2\\
0 & 2 & 2\\
2 & 2 & 4
\end{bmatrix}.
$$

## 2. Eigenvalues và right singular vectors

Ta tìm eigenvalues của $A^\top A$:

$$
\lambda_1 = 6,\qquad
\lambda_2 = 2,\qquad
\lambda_3 = 0,
$$

và sắp xếp theo thứ tự giảm dần:

$$
6 \geq 2 \geq 0.
$$

Một bộ eigenvectors trực chuẩn tương ứng là:

$$
v_1=\frac{1}{\sqrt{6}}
\begin{bmatrix}
1\\
1\\
2
\end{bmatrix},
\qquad
v_2=\frac{1}{\sqrt{2}}
\begin{bmatrix}
1\\
-1\\
0
\end{bmatrix},
\qquad
v_3=\frac{1}{\sqrt{3}}
\begin{bmatrix}
1\\
1\\
-1
\end{bmatrix}.
$$

Các vector này đôi một trực giao và đều có độ dài bằng 1. Vì $v_i$ là các eigenvectors của $A^\top A$, chúng chính là các right singular vectors của $A$.

## 3. Singular values

Singular values được tính bởi

$$
\sigma_i=\sqrt{\lambda_i}.
$$

Vậy

$$
\sigma_1=\sqrt{6},\qquad
\sigma_2=\sqrt{2},\qquad
\sigma_3=0.
$$

## 4. Tính left singular vectors $u_i$

Với mỗi $\sigma_i > 0$:

$$
u_i=\frac{Av_i}{\sigma_i}.
$$

Với

$$
v_1=\frac{1}{\sqrt{6}}
\begin{bmatrix}
1\\
1\\
2
\end{bmatrix},
$$

ta có

$$
Av_1=
\frac{1}{\sqrt{6}}
\begin{bmatrix}
3\\
3\\
3\\
3
\end{bmatrix},
\qquad
u_1=\frac{Av_1}{\sqrt{6}}=
\begin{bmatrix}
1/2\\
1/2\\
1/2\\
1/2
\end{bmatrix}.
$$

Với

$$
v_2=\frac{1}{\sqrt{2}}
\begin{bmatrix}
1\\
-1\\
0
\end{bmatrix},
$$

ta có

$$
Av_2=
\frac{1}{\sqrt{2}}
\begin{bmatrix}
1\\
-1\\
1\\
-1
\end{bmatrix},
\qquad
u_2=\frac{Av_2}{\sqrt{2}}=
\begin{bmatrix}
1/2\\
-1/2\\
1/2\\
-1/2
\end{bmatrix}.
$$

Vì $\sigma_3 = 0$, ta không thể tính

$$
u_3=\frac{Av_3}{\sigma_3},
$$

do phép chia cho 0 không xác định. Thay vào đó, để viết Full SVD, ta bổ sung thêm hai vector trực chuẩn trong phần bù trực giao của $u_1$ và $u_2$:

$$
u_3=\frac{1}{\sqrt{2}}
\begin{bmatrix}
1\\
0\\
-1\\
0
\end{bmatrix},
\qquad
u_4=\frac{1}{\sqrt{2}}
\begin{bmatrix}
0\\
1\\
0\\
-1
\end{bmatrix}.
$$

## 5. Full SVD

Ta có

$$
U=
\begin{bmatrix}
1/2 & 1/2 & 1/\sqrt{2} & 0\\
1/2 & -1/2 & 0 & 1/\sqrt{2}\\
1/2 & 1/2 & -1/\sqrt{2} & 0\\
1/2 & -1/2 & 0 & -1/\sqrt{2}
\end{bmatrix},
$$

$$
\Sigma=
\begin{bmatrix}
\sqrt{6} & 0 & 0\\
0 & \sqrt{2} & 0\\
0 & 0 & 0\\
0 & 0 & 0
\end{bmatrix},
$$

$$
V=
\begin{bmatrix}
1/\sqrt{6} & 1/\sqrt{2} & 1/\sqrt{3}\\
1/\sqrt{6} & -1/\sqrt{2} & 1/\sqrt{3}\\
2/\sqrt{6} & 0 & -1/\sqrt{3}
\end{bmatrix}.
$$

Khi đó, Full SVD của ma trận $A$ là

$$
A = U \Sigma V^\top.
$$

Kích thước của các ma trận là

$$
U \in \mathbb{R}^{4 \times 4}, \qquad
\Sigma \in \mathbb{R}^{4 \times 3}, \qquad
V^\top \in \mathbb{R}^{3 \times 3}.
$$

## 6. Reduced SVD

Vì $A$ có rank bằng 2, Reduced SVD chỉ giữ hai singular values khác 0:

$$
U_r=
\begin{bmatrix}
1/2 & 1/2\\
1/2 & -1/2\\
1/2 & 1/2\\
1/2 & -1/2
\end{bmatrix},
$$

$$
\Sigma_r=
\begin{bmatrix}
\sqrt{6} & 0\\
0 & \sqrt{2}
\end{bmatrix},
$$

$$
V_r^\top=
\begin{bmatrix}
1/\sqrt{6} & 1/\sqrt{6} & 2/\sqrt{6}\\
1/\sqrt{2} & -1/\sqrt{2} & 0
\end{bmatrix}.
$$

Do đó,

$$
A = U_r \Sigma_r V_r^\top.
$$

Kích thước của các ma trận là:

$$
U_r \in \mathbb{R}^{4 \times 2}, \qquad
\Sigma_r \in \mathbb{R}^{2 \times 2}, \qquad
V_r^\top \in \mathbb{R}^{2 \times 3}.
$$

In [5]:
import numpy as np

A = np.array([
    [1, 0, 1],
    [0, 1, 1],
    [1, 0, 1],
    [0, 1, 1],
], dtype=float)

sqrt2 = np.sqrt(2)
sqrt3 = np.sqrt(3)
sqrt6 = np.sqrt(6)

U = np.array([
    [1/2,  1/2,  1/sqrt2,  0],
    [1/2, -1/2,  0,        1/sqrt2],
    [1/2,  1/2, -1/sqrt2,  0],
    [1/2, -1/2,  0,       -1/sqrt2],
])

Sigma = np.array([
    [sqrt6, 0,     0],
    [0,     sqrt2, 0],
    [0,     0,     0],
    [0,     0,     0],
])

V = np.array([
    [1/sqrt6,  1/sqrt2,  1/sqrt3],
    [1/sqrt6, -1/sqrt2,  1/sqrt3],
    [2/sqrt6,  0,       -1/sqrt3],
])

Ur = U[:, :2]
Sigmar = Sigma[:2, :2]
Vrt = V[:, :2].T

print('A^T A =')
print(A.T @ A)
print('\nU^T U =')
print(np.round(U.T @ U, 6))
print('\nV^T V =')
print(np.round(V.T @ V, 6))
print('\nU Sigma V^T =')
print(np.round(U @ Sigma @ V.T, 6))
print('\nUr Sigmar Vrt =')
print(np.round(Ur @ Sigmar @ Vrt, 6))
print('\nFull SVD correct:', np.allclose(U @ Sigma @ V.T, A))
print('Reduced SVD correct:', np.allclose(Ur @ Sigmar @ Vrt, A))

A^T A =
[[2. 0. 2.]
 [0. 2. 2.]
 [2. 2. 4.]]

U^T U =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

V^T V =
[[ 1.  0. -0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]

U Sigma V^T =
[[1. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 1.]]

Ur Sigmar Vrt =
[[1. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 1.]]

Full SVD correct: True
Reduced SVD correct: True


## 7. Giải thích cho Câu 1

- Có một singular value bằng 0 vì $A$ có 3 cột nhưng chỉ có rank 2. Nói cách khác, $A^\top A$ có một eigenvalue bằng 0, nên singular value tương ứng cũng bằng 0.

- Right singular vector ứng với singular value 0 là

$$
v_3=\frac{1}{\sqrt{3}}
\begin{bmatrix}
1\\
1\\
-1
\end{bmatrix}.
$$

Ta có

$$
Av_3=0,
$$

nên $v_3$ nằm trong null space của $A$. Điều này cũng phản ánh quan hệ tuyến tính giữa các cột:

$$
a_1+a_2-a_3=0.
$$

- Reduced SVD vẫn tái tạo chính xác $A$ vì thành phần bị bỏ đi có singular value bằng 0. Thành phần đó đóng góp

$$
0 \cdot u_3v_3^\top = 0,
$$

nên việc bỏ nó không làm thay đổi ma trận được tái tạo.

# Câu 2. Chọn $k$ cho Truncated SVD bằng tỷ lệ năng lượng

Cho các singular values:

$$
\sigma_1 = 12,\qquad
\sigma_2 = 5,\qquad
\sigma_3 = 3,\qquad
\sigma_4 = 1.
$$

Vì cả 4 singular values đều khác 0 nên

$$
\mathrm{rank}(X) = 4.
$$

## 1. Tổng năng lượng

Năng lượng của từng singular value là bình phương của nó:

$$
\sigma_1^2 = 12^2 = 144,
$$

$$
\sigma_2^2 = 5^2 = 25,
$$

$$
\sigma_3^2 = 3^2 = 9,
$$

$$
\sigma_4^2 = 1^2 = 1.
$$

Tổng năng lượng:

$$
E_{\text{total}} = 144 + 25 + 9 + 1 = 179.
$$

## 2. Tỷ lệ năng lượng giữ lại

$$
R(k)=\frac{\sum_{i=1}^{k}\sigma_i^2}{\sum_{i=1}^{4}\sigma_i^2}.
$$

| $k$ | Năng lượng giữ lại | Tỷ lệ $R(k)$ |
|:---:|:------------------:|:------------:|
| 1 | 144 | $144/179 = 0.8045 = 80.45\%$ |
| 2 | 169 | $169/179 = 0.9441 = 94.41\%$ |
| 3 | 178 | $178/179 = 0.9944 = 99.44\%$ |
| 4 | 179 | $179/179 = 1.0000 = 100.00\%$ |

Do đó, $k$ nhỏ nhất để giữ ít nhất một tỷ lệ năng lượng cho trước là:

| Mức năng lượng yêu cầu | $k$ nhỏ nhất | Giải thích |
|:----------------------:|:------------:|:-----------|
| 80% | 1 | $R(1)=80.45\%$ |
| 90% | 2 | $R(1)<90\%$, $R(2)=94.41\%$ |
| 95% | 3 | $R(2)<95\%$, $R(3)=99.44\%$ |
| 99% | 3 | $R(3)=99.44\%$ |

## 3. Sai số Frobenius của xấp xỉ hạng $k$

Với $k = 1, 2, 3$:

$$
\|X - X_k\|_F = \sqrt{\sum_{i=k+1}^{4}\sigma_i^2}.
$$

Tính lần lượt:

$$
\|X - X_1\|_F = \sqrt{25 + 9 + 1} = \sqrt{35} \approx 5.9161,
$$

$$
\|X - X_2\|_F = \sqrt{9 + 1} = \sqrt{10} \approx 3.1623,
$$

$$
\|X - X_3\|_F = \sqrt{1} = 1.
$$

| $k$ | $R(k)$ | $\|X - X_k\|_F$ |
|:---:|:------:|:---------------:|
| 1 | 80.45% | $\sqrt{35} \approx 5.9161$ |
| 2 | 94.41% | $\sqrt{10} \approx 3.1623$ |
| 3 | 99.44% | $1$ |

In [6]:
sigma = np.array([12, 5, 3, 1], dtype=float)
energy = sigma ** 2
total_energy = energy.sum()
cumulative_energy = np.cumsum(energy)
ratios = cumulative_energy / total_energy

print('Rank:', np.count_nonzero(sigma))
print('Total energy:', total_energy)

print('\nEnergy table')
for k, retained, ratio in zip(range(1, 5), cumulative_energy, ratios):
    print(f'k={k}: retained={retained:.0f}, R(k)={ratio:.4f} ({ratio:.2%})')

print('\nSmallest k by threshold')
for threshold in [0.80, 0.90, 0.95, 0.99]:
    k_min = np.argmax(ratios >= threshold) + 1
    print(f'{threshold:.0%}: k={k_min}')

print('\nFrobenius errors')
for k in [1, 2, 3]:
    error = np.sqrt(energy[k:].sum())
    print(f'k={k}: error={error:.4f}')

Rank: 4
Total energy: 179.0

Energy table
k=1: retained=144, R(k)=0.8045 (80.45%)
k=2: retained=169, R(k)=0.9441 (94.41%)
k=3: retained=178, R(k)=0.9944 (99.44%)
k=4: retained=179, R(k)=1.0000 (100.00%)

Smallest k by threshold
80%: k=1
90%: k=2
95%: k=3
99%: k=3

Frobenius errors
k=1: error=5.9161
k=2: error=3.1623
k=3: error=1.0000


## 4. Chọn $k$ khi $\sigma_4$ chủ yếu là nhiễu

Nếu $\sigma_4 = 1$ chủ yếu biểu diễn nhiễu, lựa chọn phù hợp là

$$
k = 3.
$$

Lý do: khi giữ $k = 3$, ta giữ được

$$
R(3) = 99.44\%
$$

năng lượng, sai số còn lại là $1$, và thành phần bị bỏ chính là thành phần được giả định là nhiễu. Vì vậy, $k = 3$ vừa giữ gần như toàn bộ cấu trúc chính của dữ liệu, vừa loại bỏ nhiễu một cách hiệu quả.

## 5. Trả lời câu hỏi lý thuyết?

Vì sao singular values phải được sắp xếp giảm dần?

Singular values được sắp xếp giảm dần để các thành phần quan trọng nhất đứng trước. Khi dùng Truncated SVD, ta chỉ cần lấy k thành phần đầu tiên là đã lấy được các hướng chứa nhiều năng lượng (thông tin) nhất của dữ liệu.

Giữ càng nhiều singular values có phải lúc nào cũng tốt hơn không?

Không phải lúc nào cũng tốt hơn. Giữ nhiều singular values giúp tái tạo dữ liệu chính xác hơn, nhưng cũng làm giảm mức độ nén, tăng chi phí lưu trữ và tính toán, đồng thời có thể giữ lại cả nhiễu trong dữ liệu.

Sự đánh đổi giữa tỷ lệ năng lượng và mức độ nén dữ liệu là gì?

Nếu chọn k lớn, tỷ lệ năng lượng giữ lại cao và sai số tái tạo nhỏ, nhưng dữ liệu được nén ít hơn. Ngược lại, nếu chọn k nhỏ, dữ liệu được nén mạnh hơn và mô hình đơn giản hơn, nhưng sẽ mất nhiều thông tin hơn. Vì vậy, cần lựa chọn k phù hợp với mục tiêu của bài toán, chẳng hạn như ưu tiên tái tạo chính xác, giảm nhiễu hay tiết kiệm bộ nhớ và chi phí tính toán.